apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-test
  labels:
    app: react-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-test
  template:
    metadata:
      labels:
        app: react-test
    spec:
      containers:
      - name: react-test
        image: docker.io/fapathe/pipeline:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-test-service
spec:
  selector:
    app: react-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: react-test-route
spec:
  to:
    kind: Service
    name: react-test-service
  port:
    targetPort: 80
